### ISSUE TITLE
Not compatible with pandas 2.0.0

### ISSUE THREAD

**Issue by JuanCruzC97** [MaxHalford/prince#144]
I'm having dependency conflicts when trying to install prince and pandas==2.0.0 in the same environment.

**Comment by MaxHalford** [comment]
Good catch, I hadn't noticed. I just published a version 0.10.2 which should fix this issue. Could you check again? If it still doesn't work, please let me know.

**Comment by MaxHalford** [comment]
I create a dummy project with the following `pyproject.toml`, ran `poetry install`, and it ran successfully:

```toml
[tool.poetry]
name = "test-p"
version = "0.1.0"
description = ""
authors = ["Max Halford <maxhalford25@gmail.com>"]
readme = "README.md"
packages = [{include = "test_p"}]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^2.0.0"
prince = "^0.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
